require 'rake/clean'

CLEAN.include '*.o', 'Makefile', 'mkmf.log'
CLOBBER.include 'fft_api.so', 'fft_api.bundle'

task :default => ['fft_api.bundle']

file 'fft_api.bundle' => ['Makefile'] do
  sh "make"
end

file 'Makefile' do
  ruby "extconf.rb"
end
