require 'rake/clean'

CLEAN.include '*.o', 'Makefile', 'mkmf.log'
CLOBBER.include 'fft.so', 'fft.bundle'

task :default => ['fft.bundle']

file 'fft.bundle' => ['Makefile'] do
  sh "make"
end

file 'Makefile' do
  ruby "extconf.rb"
end
